name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0

    - name: Set up Go
      uses: actions/setup-go@v6.0.0
      with:
        go-version: '1.25'

    - name: Build
      run: make build
