name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Go
        uses: actions/setup-go@v6.0.0
        with:
          go-version: '1.25'

      - name: Build for all platforms
        run: |
          make build-linux
          make build-windows
          make build-macos

      - name: Create Release
        uses: softprops/action-gh-release@v2.3.4
        with:
          files: |
            nvidia-ai-chat-linux-amd64
            nvidia-ai-chat-windows-amd64.exe
            nvidia-ai-chat-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
